"""Veritas: evidence-first auditing for empirical social science research."""

from .audit import AuditEngine
from .benchmark import (
    BenchmarkCase,
    BenchmarkSplit,
    CertificationPolicy,
    CertificationReport,
    PaperAuditOutcome,
    ProductionCalibrationCertificate,
    assign_paper_split,
    benchmark_manifest_sha256,
    certification_policy_sha256,
    certification_report_sha256,
    evaluate_hard_alert_certification,
    issue_production_calibration_certificate,
)
from .claim_identity import (
    ClaimEstimateAlignment,
    EstimandIdentity,
    IdentityMatch,
    ScaleTransformation,
    add_claim_estimate_candidate,
    build_claim_estimate_alignment,
    compare_estimand_identity,
    link_empirical_evidence_chain,
    normalize_estimand_identity,
    normalize_identity_label,
    normalize_scale_transformation,
    require_cross_location_e3_identity,
)
from .claim_identity_benchmark import (
    ClaimIdentityBenchmarkReport,
    ClaimIdentityGold,
    ClaimIdentityPrediction,
    evaluate_claim_identity,
)
from .claims import (
    ArtifactRef,
    ClaimEdge,
    ClaimNode,
    ClaimRole,
    EvidenceNode,
    EvidenceNodeKind,
    ExtractedField,
    RelationType,
    StatisticalClaimGraph,
    StatisticalObjectNode,
)
from .corpus import (
    AccessTier,
    ArticleFamilySplitLock,
    ClaimExpectation,
    ClaimGroundTruth,
    CorpusManifest,
    CorpusPaper,
    GroundTruthBasis,
    assign_article_family_split,
)
from .extraction import (
    ConformalCalibration,
    ConformalExtractionGate,
    ExtractionCandidate,
    ExtractionDecision,
    ExtractionResolution,
)
from .extraction_benchmark import (
    ExtractionBenchmarkReport,
    ExtractionGoldTarget,
    ExtractionPrediction,
    ExtractionSelectivityCurve,
    ExtractionSelectivityPoint,
    ExtractionTargetOutcome,
    build_extraction_selectivity_curve,
    evaluate_extraction_benchmark,
)
from .extraction_calibration import (
    ExtractionTestEvaluationLock,
    ExtractionThresholdObservation,
    ExtractionThresholdPolicy,
    FrozenExtractionThreshold,
    lock_test_evaluation,
    select_development_threshold,
)
from .extraction_review import (
    ExtractionAdjudication,
    ExtractionGoldManifest,
    ExtractionReviewRecord,
    ExtractionReviewSubmission,
    ExtractionReviewTarget,
    resolve_extraction_reviews,
)
from .extraction_review_packet import (
    ExtractionReviewerPacket,
    ExtractionReviewPacketTarget,
    build_blinded_seed_review_packets,
)
from .extraction_test_seal import ExtractionTestSetSeal, seal_extraction_test_set
from .group_stats import GroupSummary, OneWayAnovaComparison, TwoGroupComparison
from .ingestion import (
    CalibrationScope,
    DetectorInputEnvelope,
    EvidenceKind,
    EvidenceLedger,
    IngestionProtocol,
    ObjectDraft,
    PromotionDecision,
    PromotionReport,
    PromotionSpec,
    ResolvedEvidence,
)
from .meta_analysis import MetaAnalysisSummary, MetaStudyEffect
from .methodology import MethodAnchor, get_method_anchor, methodology_snapshot_sha256
from .models import (
    AuditSummary,
    CheckResult,
    CorrelationMatrix,
    DIDDesign,
    DiscreteSummary,
    Finding,
    IVDesign,
    LogitResult,
    MediationResult,
    RDDDesign,
    RegressionResult,
    ReportedNumber,
    SamplePartition,
    SourceLocation,
    StandardizedRegressionReconstruction,
)
from .runtime import numerical_backend_sha256, numerical_backend_versions
from .sem import SEMFitSummary, SEMNestedComparison
from .specifications import (
    Specification,
    SpecificationConstraint,
    SpecificationEstimate,
    SpecificationRobustnessSummary,
    SpecificationSpace,
    summarize_specification_robustness,
)
from .types import EvidenceFamily, EvidenceGrade, Materiality

__all__ = [
    "AccessTier",
    "ArticleFamilySplitLock",
    "ArtifactRef",
    "AuditEngine",
    "AuditSummary",
    "BenchmarkCase",
    "BenchmarkSplit",
    "CalibrationScope",
    "CertificationPolicy",
    "CertificationReport",
    "CheckResult",
    "ClaimEdge",
    "ClaimEstimateAlignment",
    "ClaimExpectation",
    "ClaimGroundTruth",
    "ClaimIdentityBenchmarkReport",
    "ClaimIdentityGold",
    "ClaimIdentityPrediction",
    "ClaimNode",
    "ClaimRole",
    "ConformalCalibration",
    "ConformalExtractionGate",
    "CorpusManifest",
    "CorpusPaper",
    "CorrelationMatrix",
    "DIDDesign",
    "DetectorInputEnvelope",
    "DiscreteSummary",
    "EstimandIdentity",
    "EvidenceFamily",
    "EvidenceGrade",
    "EvidenceKind",
    "EvidenceLedger",
    "EvidenceNode",
    "EvidenceNodeKind",
    "ExtractedField",
    "ExtractionAdjudication",
    "ExtractionBenchmarkReport",
    "ExtractionCandidate",
    "ExtractionDecision",
    "ExtractionGoldManifest",
    "ExtractionGoldTarget",
    "ExtractionPrediction",
    "ExtractionResolution",
    "ExtractionReviewPacketTarget",
    "ExtractionReviewRecord",
    "ExtractionReviewSubmission",
    "ExtractionReviewTarget",
    "ExtractionReviewerPacket",
    "ExtractionSelectivityCurve",
    "ExtractionSelectivityPoint",
    "ExtractionTargetOutcome",
    "ExtractionTestEvaluationLock",
    "ExtractionTestSetSeal",
    "ExtractionThresholdObservation",
    "ExtractionThresholdPolicy",
    "Finding",
    "FrozenExtractionThreshold",
    "GroundTruthBasis",
    "GroupSummary",
    "IVDesign",
    "IdentityMatch",
    "IngestionProtocol",
    "LogitResult",
    "Materiality",
    "MediationResult",
    "MetaAnalysisSummary",
    "MetaStudyEffect",
    "MethodAnchor",
    "ObjectDraft",
    "OneWayAnovaComparison",
    "PaperAuditOutcome",
    "ProductionCalibrationCertificate",
    "PromotionDecision",
    "PromotionReport",
    "PromotionSpec",
    "RDDDesign",
    "RegressionResult",
    "RelationType",
    "ReportedNumber",
    "ResolvedEvidence",
    "SEMFitSummary",
    "SEMNestedComparison",
    "SamplePartition",
    "ScaleTransformation",
    "SourceLocation",
    "Specification",
    "SpecificationConstraint",
    "SpecificationEstimate",
    "SpecificationRobustnessSummary",
    "SpecificationSpace",
    "StandardizedRegressionReconstruction",
    "StatisticalClaimGraph",
    "StatisticalObjectNode",
    "TwoGroupComparison",
    "add_claim_estimate_candidate",
    "assign_article_family_split",
    "assign_paper_split",
    "benchmark_manifest_sha256",
    "build_blinded_seed_review_packets",
    "build_claim_estimate_alignment",
    "build_extraction_selectivity_curve",
    "certification_policy_sha256",
    "certification_report_sha256",
    "compare_estimand_identity",
    "evaluate_claim_identity",
    "evaluate_extraction_benchmark",
    "evaluate_hard_alert_certification",
    "get_method_anchor",
    "issue_production_calibration_certificate",
    "link_empirical_evidence_chain",
    "lock_test_evaluation",
    "methodology_snapshot_sha256",
    "normalize_estimand_identity",
    "normalize_identity_label",
    "normalize_scale_transformation",
    "numerical_backend_sha256",
    "numerical_backend_versions",
    "require_cross_location_e3_identity",
    "resolve_extraction_reviews",
    "seal_extraction_test_set",
    "select_development_threshold",
    "summarize_specification_robustness",
]

__version__ = "0.12.0"
