"""Veritas: evidence-first auditing for empirical social science research."""

from .audit import AuditEngine
from .benchmark import (
    BenchmarkCase,
    BenchmarkSplit,
    CertificationPolicy,
    CertificationReport,
    PaperAuditOutcome,
    assign_paper_split,
    benchmark_manifest_sha256,
    evaluate_hard_alert_certification,
)
from .claims import (
    ArtifactRef,
    ClaimEdge,
    ClaimNode,
    ClaimRole,
    ExtractedField,
    RelationType,
    StatisticalClaimGraph,
    StatisticalObjectNode,
)
from .corpus import (
    AccessTier,
    ClaimExpectation,
    ClaimGroundTruth,
    CorpusManifest,
    CorpusPaper,
    GroundTruthBasis,
    assign_article_family_split,
)
from .extraction import (
    ConformalCalibration,
    ConformalExtractionGate,
    ExtractionCandidate,
    ExtractionDecision,
    ExtractionResolution,
)
from .group_stats import GroupSummary, OneWayAnovaComparison, TwoGroupComparison
from .ingestion import (
    DetectorInputEnvelope,
    EvidenceKind,
    EvidenceLedger,
    IngestionProtocol,
    ObjectDraft,
    PromotionDecision,
    PromotionReport,
    PromotionSpec,
    ResolvedEvidence,
)
from .meta_analysis import MetaAnalysisSummary, MetaStudyEffect
from .methodology import MethodAnchor, get_method_anchor, methodology_snapshot_sha256
from .models import (
    AuditSummary,
    CheckResult,
    CorrelationMatrix,
    DIDDesign,
    DiscreteSummary,
    Finding,
    IVDesign,
    LogitResult,
    MediationResult,
    RDDDesign,
    RegressionResult,
    ReportedNumber,
    SamplePartition,
    SourceLocation,
    StandardizedRegressionReconstruction,
)
from .runtime import numerical_backend_sha256, numerical_backend_versions
from .sem import SEMFitSummary, SEMNestedComparison
from .specifications import (
    Specification,
    SpecificationConstraint,
    SpecificationEstimate,
    SpecificationRobustnessSummary,
    SpecificationSpace,
    summarize_specification_robustness,
)
from .types import EvidenceFamily, EvidenceGrade, Materiality

__all__ = [
    "AccessTier",
    "ArtifactRef",
    "AuditEngine",
    "AuditSummary",
    "BenchmarkCase",
    "BenchmarkSplit",
    "CertificationPolicy",
    "CertificationReport",
    "CheckResult",
    "ClaimEdge",
    "ClaimExpectation",
    "ClaimGroundTruth",
    "ClaimNode",
    "ClaimRole",
    "ConformalCalibration",
    "ConformalExtractionGate",
    "CorpusManifest",
    "CorpusPaper",
    "CorrelationMatrix",
    "DIDDesign",
    "DetectorInputEnvelope",
    "DiscreteSummary",
    "EvidenceFamily",
    "EvidenceGrade",
    "EvidenceKind",
    "EvidenceLedger",
    "ExtractedField",
    "ExtractionCandidate",
    "ExtractionDecision",
    "ExtractionResolution",
    "Finding",
    "GroundTruthBasis",
    "GroupSummary",
    "IVDesign",
    "IngestionProtocol",
    "LogitResult",
    "Materiality",
    "MediationResult",
    "MetaAnalysisSummary",
    "MetaStudyEffect",
    "MethodAnchor",
    "ObjectDraft",
    "OneWayAnovaComparison",
    "PaperAuditOutcome",
    "PromotionDecision",
    "PromotionReport",
    "PromotionSpec",
    "RDDDesign",
    "RegressionResult",
    "RelationType",
    "ReportedNumber",
    "ResolvedEvidence",
    "SEMFitSummary",
    "SEMNestedComparison",
    "SamplePartition",
    "SourceLocation",
    "Specification",
    "SpecificationConstraint",
    "SpecificationEstimate",
    "SpecificationRobustnessSummary",
    "SpecificationSpace",
    "StandardizedRegressionReconstruction",
    "StatisticalClaimGraph",
    "StatisticalObjectNode",
    "TwoGroupComparison",
    "assign_article_family_split",
    "assign_paper_split",
    "benchmark_manifest_sha256",
    "evaluate_hard_alert_certification",
    "get_method_anchor",
    "methodology_snapshot_sha256",
    "numerical_backend_sha256",
    "numerical_backend_versions",
    "summarize_specification_robustness",
]

__version__ = "0.8.0"
